### ISSUE TITLE
图片加密后无法恢复

### ISSUE THREAD

**Issue by Conyhui** [Scorpio-y/RGB-Image-encryption-based-on-chaotic-system-and-DNA-algorithm#1]
你好，最近跑了你的代码，然而main_jiami后的图像，在mian_jiemi后无法恢复，已知加密的9个密钥和解密的9个密钥是一致的，代码也细细看了，没找到问题，想知道为什么，哭

**Comment by Scorpio-y** [comment]
你好，请问你用的是我提供的lena.png图片跑的代码吗
